# .gitlab-ci.yml

build site:
  image: node:10
  stage: build
  script:
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

unit test:
  image: node:10
  stage: test
  script:
    - yarn install --frozen-lockfile
    - yarn test:unit

e2e test:chrome:
  image: node:10
  services:
    - selenium/standalone-chrome
  stage: test
  script:
    - yarn install --frozen-lockfile
    - yarn test:e2e --env chrome --headless

e2e test:firefox:
  image: node:10
  services:
    - selenium/standalone-firefox
  stage: test
  script:
    - yarn install --frozen-lockfile
    - yarn test:e2e --env firefox --headless

deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ user@server.com:/your/project/path/
